name: lint
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install --user codespell[toml] ruff
    - run: codespell
    - run: ruff check --output-format=github
